#!/bin/bash
set +x
set -e
. .colors.sh

BASEDIR=$PWD
. $BASEDIR/io.sh 1 0 1 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES
input_zip=${INPUTS1}


## PARAMETERS VARIABLES


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT

    
pushd .
sh concat.sh input/test.txt input/test2.txt
popd

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh